name: contractions
description: "Aplicativo para registro de contrações uterinas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.1
  intl: ^0.20.2
  provider: ^6.1.5
  table_calendar: ^3.1.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
